# Site settings
title: Travel
email: madeleine333@naver.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: de91a8 #80B3FF
  secondary: b4aeb0 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: cse_kut
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/madeleine0829
  - title: facebook
    url: https://facebook.com/profile.php?id=100007062280143&fref=ts
  - title: github
    url: http://github.com/whemsthf123/whemsthf123.github.com
# Postal address (add as many lines as necessary)
address:
  - line: 대한민국 충청남도 천안시 동남구 병천면 충절로 가전리 1600
  - line: 한국기술교육대학교

# Credits content
credits: 'created by <a href="http://cse.koreatech.ac.kr">CSE Students</a>.'

# Build settings
markdown: kramdown
permalink: pretty
